Disable auto-discovery for setuptools
With the latest setuptools release (61.0.0) ansible-role-atos-hsm's
package build command (python3 setup.py sdist bdist_wheel) started to
fail:

error: Multiple top-level packages discovered in a flat-layout:
['defaults', 'handlers', 'templates', 'releasenotes'].

This issue is mentioned in setuptools bug 3197 [1], and the suggested
workaround is to disable auto-discovery by adding 'py_modules=[]' in
setup.py.

ansible-lint also released a new version (6.0.0), which has new rules
that blocks the gate. As a workaround, this patch caps ansible-lint
version <6.0.0 to unblock the gate.

[1] https://github.com/pypa/setuptools/issues/3197

Change-Id: I3f827b3ed855ff46292dee7b21b74a622adc472d
(cherry picked from commit f5c86dff4ee246f0ecbfb2d753e2c90912e7bb02)